add_lunch_combo aosp_k3gxx-eng
add_lunch_combo aosp_k3gxx-userdebug
add_lunch_combo du_k3gxx-eng
add_lunch_combo du_k3gxx-userdebug
add_lunch_combo lineage_k3gxx-eng
add_lunch_combo lineage_k3gxx-userdebug